services:
  - type: web
    name: hotel-app
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -t 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
